/**
 * Application schema. Auth tables (user/session/organization/member/…) are
 * generated by better-auth into ./auth-schema.ts and referenced here by id.
 *
 * Every learned row carries the PROVENANCE SPINE (see `spine()`): status,
 * confidence, source, verbatim evidence. Nothing about a human is ever stored
 * without saying where it came from.
 */
import { sql } from 'drizzle-orm';
import {
  pgTable, text, timestamp, boolean, integer, real, jsonb, uuid, primaryKey, index, uniqueIndex, unique, customType,
} from 'drizzle-orm/pg-core';
import type { AvatarRecipe, PersonaArtifact } from '@opersona/shared';

// ─── helpers ────────────────────────────────────────────────────────────────
import { randomBytes } from 'node:crypto';
const ALPHABET = 'abcdefghijkmnpqrstuvwxyz23456789'; // no 0/o/1/l
export function shortId(len = 7): string { const b = randomBytes(len); let s = ''; for (let i = 0; i < len; i++) s += ALPHABET[b[i]! % ALPHABET.length]; return s; }
const tsvector = customType<{ data: string }>({ dataType: () => 'tsvector' });
const now = () => timestamp('created_at', { withTimezone: true }).defaultNow().notNull();
const updated = () => timestamp('updated_at', { withTimezone: true }).defaultNow().notNull();

export type LearnedStatus = 'candidate' | 'confirmed' | 'disputed' | 'retired';
export type SourceKind = 'conversation' | 'teach' | 'correction' | 'document' | 'reflection' | 'admin' | 'import' | 'interview';
/** `ref` points at the exact source for click-through, e.g. 'interview:<answerId>'. */
export interface Evidence { quote: string; turn_id?: string; ref?: string }

/** Provenance spine mixed into every learned-layer table. */
const spine = () => ({
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  status: text('status').$type<LearnedStatus>().notNull().default('candidate'),
  confidence: real('confidence').notNull().default(0.5),
  sourceKind: text('source_kind').$type<SourceKind>().notNull(),
  sourceRef: text('source_ref'),
  evidence: jsonb('evidence').$type<Evidence[]>().notNull().default([]),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
  updatedAt: updated(),
  lastReinforcedAt: timestamp('last_reinforced_at', { withTimezone: true }),
  reinforceCount: integer('reinforce_count').notNull().default(0),
  supersedes: uuid('supersedes'),
});

// ─── org settings ───────────────────────────────────────────────────────────
export const orgSettings = pgTable('org_settings', {
  orgId: text('org_id').primaryKey(),
  /** AES-GCM encrypted Anthropic API key (BYO). null → platform key. */
  anthropicKeyEnc: text('anthropic_key_enc'),
  chatModel: text('chat_model').notNull().default('claude-opus-5'),
  extractModel: text('extract_model').notNull().default('claude-sonnet-5'),
  condenseModel: text('condense_model').notNull().default('claude-haiku-4-5'),
  chatEffort: text('chat_effort').notNull().default('high'),
  monthlyBudgetUsd: real('monthly_budget_usd'),
  timezone: text('timezone').notNull().default('UTC'),
  /** The starred persona who runs the floor: delegates work, hires temp personas. */
  bossCloneId: uuid('boss_clone_id'),
  /** Sealed conversations: fingerprint of the user-held key (never the key). */
  sealKeyFp: text('seal_key_fp'),
  sealedAt: timestamp('sealed_at'),
  updatedAt: updated(),
});

// ─── clones ─────────────────────────────────────────────────────────────────
export const clones = pgTable('clones', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  ownerUserId: text('owner_user_id').notNull(),
  name: text('name').notNull(),
  avatarRecipe: jsonb('avatar_recipe').$type<AvatarRecipe>(),
  activeSnapshotId: uuid('active_snapshot_id'),
  /** 'member': a person's learned persona. 'hired': a temp specialist. 'imported': a materialized copy of a published persona. */
  kind: text('kind').$type<'member' | 'hired' | 'imported'>().notNull().default('member'),
  /** hired personas park here between engagements; rehiring clears it */
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: now(),
  updatedAt: updated(),
}, (t) => [
  // one learned persona per member; hired personas (kind='hired') share the hirer's owner id
  uniqueIndex('clones_org_owner_uq').on(t.orgId, t.ownerUserId).where(sql`kind = 'member'`),
  index('clones_org_idx').on(t.orgId),
]);

export const personaBriefs = pgTable('persona_briefs', {
  cloneId: uuid('clone_id').primaryKey(),
  orgId: text('org_id').notNull(),
  displayName: text('display_name').notNull().default(''),
  roleTitle: text('role_title').notNull().default(''),
  team: text('team').notNull().default(''),
  briefMd: text('brief_md').notNull().default(''),
  operatingRules: text('operating_rules').notNull().default(''),
  version: integer('version').notNull().default(1),
  updatedAt: updated(),
});

// ─── learned layers ─────────────────────────────────────────────────────────
export const facts = pgTable('facts', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  statement: text('statement').notNull(),
  tags: text('tags').array().notNull().default(sql`'{}'::text[]`),
  domain: text('domain'),
  pinned: boolean('pinned').notNull().default(false),
  shareable: boolean('shareable').notNull().default(false),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(statement,'') || ' ' || coalesce(domain,''))`),
}, (t) => [
  index('facts_clone_idx').on(t.cloneId, t.status),
  index('facts_tsv_idx').using('gin', t.tsv),
]);

export interface PlaybookStep { n: number; action: string; command?: string; check?: string; expected?: string; if_not?: string }
export const playbooks = pgTable('playbooks', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  name: text('name').notNull(),
  domain: text('domain'),
  version: integer('version').notNull().default(1),
  trigger: text('trigger').notNull(),
  preconditions: text('preconditions').array().notNull().default(sql`'{}'::text[]`),
  steps: jsonb('steps').$type<PlaybookStep[]>().notNull().default([]),
  pitfalls: text('pitfalls').array().notNull().default(sql`'{}'::text[]`),
  outcomeStats: jsonb('outcome_stats').$type<{ used: number; succeeded: number; failed: number }>().notNull().default({ used: 0, succeeded: 0, failed: 0 }),
  sourceEpisodeIds: uuid('source_episode_ids').array().notNull().default(sql`'{}'::uuid[]`),
  shareable: boolean('shareable').notNull().default(true),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(name,'') || ' ' || coalesce(trigger,'') || ' ' || coalesce(domain,''))`),
}, (t) => [
  index('playbooks_clone_idx').on(t.cloneId, t.status),
  index('playbooks_tsv_idx').using('gin', t.tsv),
]);

export const playbookRevisions = pgTable('playbook_revisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  playbookId: uuid('playbook_id').notNull(),
  version: integer('version').notNull(),
  snapshot: jsonb('snapshot').notNull(),
  diff: text('diff'),
  reason: text('reason'),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
});

export type StyleDimension = 'approach' | 'verbosity' | 'tools_preferred' | 'risk_tolerance' | 'escalation' | 'verification' | 'communication';
export interface StyleDimensionValue { value: string | string[]; score?: number; n: number; confidence: number; examples: string[] }
export const styleProfiles = pgTable('style_profiles', {
  cloneId: uuid('clone_id').primaryKey(),
  orgId: text('org_id').notNull(),
  version: integer('version').notNull().default(1),
  dimensions: jsonb('dimensions').$type<Partial<Record<StyleDimension, StyleDimensionValue>>>().notNull().default({}),
  overrides: jsonb('overrides').$type<Partial<Record<StyleDimension, string>>>().notNull().default({}),
  renderedMd: text('rendered_md').notNull().default(''),
  updatedAt: updated(),
});

export const styleObservations = pgTable('style_observations', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  dimension: text('dimension').$type<StyleDimension>().notNull(),
  observedValue: text('observed_value').notNull(),
  weight: real('weight').notNull().default(1),
}, (t) => [index('style_obs_clone_idx').on(t.cloneId, t.dimension)]);

export const episodes = pgTable('episodes', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  conversationId: uuid('conversation_id'),
  domain: text('domain'),
  title: text('title').notNull(),
  problem: text('problem').notNull().default(''),
  approachSummary: text('approach_summary').notNull().default(''),
  keyDecisions: text('key_decisions').array().notNull().default(sql`'{}'::text[]`),
  outcome: text('outcome').$type<'resolved' | 'partial' | 'unresolved' | 'unknown'>().notNull().default('unknown'),
  durationS: integer('duration_s'),
  turnCount: integer('turn_count'),
  playbookIds: uuid('playbook_ids').array().notNull().default(sql`'{}'::uuid[]`),
  factIds: uuid('fact_ids').array().notNull().default(sql`'{}'::uuid[]`),
  condensed: boolean('condensed').notNull().default(false),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(title,'') || ' ' || coalesce(problem,'') || ' ' || coalesce(approach_summary,''))`),
}, (t) => [
  index('episodes_clone_idx').on(t.cloneId, t.createdAt),
  index('episodes_tsv_idx').using('gin', t.tsv),
]);

export const condensedHistory = pgTable('condensed_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  domain: text('domain').notNull().default('general'),
  summaryMd: text('summary_md').notNull().default(''),
  coversEpisodeIds: uuid('covers_episode_ids').array().notNull().default(sql`'{}'::uuid[]`),
  version: integer('version').notNull().default(1),
  updatedAt: updated(),
}, (t) => [uniqueIndex('condensed_clone_domain_uq').on(t.cloneId, t.domain)]);

export const corrections = pgTable('corrections', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  conversationId: uuid('conversation_id'),
  taskId: uuid('task_id'),
  turnId: uuid('turn_id'),
  cloneOutput: text('clone_output').notNull().default(''),
  humanFix: text('human_fix').notNull().default(''),
  diff: text('diff'),
  kind: text('kind').$type<'factual' | 'procedural' | 'stylistic' | 'scope' | 'one_off'>().notNull().default('one_off'),
  severity: text('severity').$type<'low' | 'medium' | 'high'>().notNull().default('low'),
  lesson: text('lesson').notNull().default(''),
  scope: jsonb('scope').$type<{ domain?: string; task_type?: string }>().notNull().default({}),
  applied: jsonb('applied').$type<{ layer: string; id: string; action: string }[]>().notNull().default([]),
  standing: boolean('standing').notNull().default(false),
}, (t) => [index('corrections_clone_idx').on(t.cloneId, t.standing)]);

export const autonomyLedger = pgTable('autonomy_ledger', {
  cloneId: uuid('clone_id').notNull(),
  orgId: text('org_id').notNull(),
  taskType: text('task_type').notNull(),
  level: integer('level').notNull().default(1),
  approvedClean: integer('approved_clean').notNull().default(0),
  approvedEdited: integer('approved_edited').notNull().default(0),
  rejected: integer('rejected').notNull().default(0),
  streakClean: integer('streak_clean').notNull().default(0),
  adminCap: integer('admin_cap'),
  lastChangeAt: timestamp('last_change_at', { withTimezone: true }),
  lastChangeReason: text('last_change_reason'),
}, (t) => [primaryKey({ columns: [t.cloneId, t.taskType] })]);

export const taskReviews = pgTable('task_reviews', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  taskId: uuid('task_id').notNull(),
  taskType: text('task_type').notNull(),
  verdict: text('verdict').$type<'approved' | 'edited' | 'rejected'>().notNull(),
  editDistance: integer('edit_distance'),
  comment: text('comment'),
  reviewerUserId: text('reviewer_user_id').notNull(),
  createdAt: now(),
});

// ─── cross-cutting ──────────────────────────────────────────────────────────
export const learningEvents = pgTable('learning_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  layer: text('layer').notNull(), // fact | playbook | style | episode | correction | autonomy | brief
  targetId: text('target_id'),
  action: text('action').notNull(), // created | updated | merged | retired | disputed | promoted | demoted
  summary: text('summary').notNull(),
  before: jsonb('before'),
  after: jsonb('after'),
  confidence: real('confidence'),
  sourceKind: text('source_kind').$type<SourceKind>(),
  sourceRef: text('source_ref'),
  reviewStatus: text('review_status').$type<'pending' | 'accepted' | 'rejected' | 'edited' | 'auto'>().notNull().default('pending'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('learning_events_clone_idx').on(t.cloneId, t.reviewStatus, t.createdAt)]);

export const rejectedProposals = pgTable('rejected_proposals', {
  id: uuid('id').primaryKey().defaultRandom(),
  cloneId: uuid('clone_id').notNull(),
  layer: text('layer').notNull(),
  text: text('text').notNull(),
  createdAt: now(),
});

export const personaSnapshots = pgTable('persona_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  version: integer('version').notNull(),
  renderedPrompt: text('rendered_prompt').notNull(),
  promptHash: text('prompt_hash').notNull(),
  tokenEstimate: integer('token_estimate'),
  layerVersions: jsonb('layer_versions').notNull().default({}),
  reflectionRunId: uuid('reflection_run_id'),
  createdAt: now(),
}, (t) => [uniqueIndex('snapshots_clone_version_uq').on(t.cloneId, t.version)]);

export const reflectionRuns = pgTable('reflection_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  startedAt: now(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  status: text('status').$type<'running' | 'done' | 'aborted' | 'skipped'>().notNull().default('running'),
  reason: text('reason'),
  stats: jsonb('stats').notNull().default({}),
  backupRef: text('backup_ref'),
});

// ─── documents ──────────────────────────────────────────────────────────────
export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id'), // null → org-wide KB
  filename: text('filename').notNull(),
  mime: text('mime').notNull(),
  bytes: integer('bytes').notNull(),
  trust: text('trust').notNull().default('untrusted'),
  uploadedBy: text('uploaded_by').notNull(),
  createdAt: now(),
}, (t) => [index('documents_org_idx').on(t.orgId, t.cloneId)]);

export const documentChunks = pgTable('document_chunks', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id'),
  ord: integer('ord').notNull(),
  content: text('content').notNull(),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(content,''))`),
}, (t) => [
  index('chunks_doc_idx').on(t.documentId, t.ord),
  index('chunks_tsv_idx').using('gin', t.tsv),
]);

// ─── conversations ──────────────────────────────────────────────────────────
export const conversations = pgTable('conversations', {
  pinned: boolean('pinned').notNull().default(false),
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  /** Short public id for URLs (/c/<slug>). */
  slug: text('slug').notNull().unique().$defaultFn(() => shortId()),
  title: text('title').notNull().default('New conversation'),
  sdkSessionId: text('sdk_session_id'),
  /** claude = plain Claude (the persona only learns from it); clone = answer AS the clone (to test it). */
  mode: text('mode').$type<'claude' | 'clone'>().notNull().default('claude'),
  /** Per-conversation overrides; null → org default. */
  model: text('model'),
  effort: text('effort').$type<'low' | 'medium' | 'high' | 'xhigh' | 'max'>(),
  status: text('status').$type<'live' | 'idle' | 'closed'>().notNull().default('idle'),
  /** Per-conversation working directory for code execution + file outputs (null = legacy per-clone workspace). */
  cwd: text('cwd'),
  /** POWER: absolute path of the granted folder this conversation runs in (null = sandbox).
   *  Bound at creation, immutable after the first message. */
  workspace: text('workspace'),
  /** The cwd the current sdk_session_id was minted in — resume only when it matches. */
  resumeCwd: text('resume_cwd'),
  extractedAt: timestamp('extracted_at', { withTimezone: true }),
  lastActivityAt: timestamp('last_activity_at', { withTimezone: true }).defaultNow().notNull(),
  createdAt: now(),
}, (t) => [index('conversations_clone_idx').on(t.cloneId, t.lastActivityAt)]);

export const turns = pgTable('turns', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id').notNull(),
  orgId: text('org_id').notNull(),
  role: text('role').$type<'user' | 'assistant' | 'system'>().notNull(),
  content: text('content').notNull(), // redacted
  toolUses: jsonb('tool_uses').$type<{ id: string; name: string; input: unknown; ok?: boolean; preview?: string }[]>().notNull().default([]),
  /** Files created/changed in the conversation workdir during this assistant turn. */
  files: jsonb('files').$type<{ path: string; size: number }[]>(),
  editedContent: text('edited_content'),
  createdAt: now(),
}, (t) => [index('turns_conv_idx').on(t.conversationId, t.createdAt)]);

export const sessionCosts = pgTable('session_costs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id'),
  kind: text('kind').notNull().default('chat'), // chat | extract | reflect | avatar | task
  model: text('model'),
  promptHash: text('prompt_hash'),
  inputTokens: integer('input_tokens').notNull().default(0),
  outputTokens: integer('output_tokens').notNull().default(0),
  cacheReadInputTokens: integer('cache_read_input_tokens').notNull().default(0),
  cacheCreationInputTokens: integer('cache_creation_input_tokens').notNull().default(0),
  costUsd: real('cost_usd'),
  createdAt: now(),
}, (t) => [index('session_costs_org_idx').on(t.orgId, t.createdAt)]);

export const approvals = pgTable('approvals', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id'),
  kind: text('kind').$type<'tool' | 'question'>().notNull().default('tool'),
  tool: text('tool'),
  input: jsonb('input'),
  question: text('question'),
  options: text('options').array(),
  status: text('status').$type<'pending' | 'allowed' | 'denied' | 'answered' | 'expired'>().notNull().default('pending'),
  answer: text('answer'),
  updatedInput: jsonb('updated_input'),
  resolvedBy: text('resolved_by'),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('approvals_clone_idx').on(t.cloneId, t.status)]);

// ─── tasks (Phase 2) ────────────────────────────────────────────────────────
export const tasks = pgTable('tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  taskType: text('task_type').notNull(),
  spec: text('spec').notNull(),
  input: jsonb('input'),
  status: text('status').$type<'queued' | 'running' | 'awaiting_review' | 'approved' | 'edited' | 'rejected' | 'done' | 'failed'>().notNull().default('queued'),
  output: text('output'),
  autonomyLevelAtRun: integer('autonomy_level_at_run'),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
  updatedAt: updated(),
});

// ─── inter-clone messages (Phase 3) ─────────────────────────────────────────
export const cloneMessages = pgTable('clone_messages', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  conversation: text('conversation').notNull(),
  inReplyTo: text('in_reply_to'),
  from: uuid('from_clone').notNull(),
  to: text('to_clone').notNull(),
  act: text('act').notNull(),
  subject: text('subject').notNull(),
  body: text('body').notNull(),
  hops: integer('hops').notNull().default(0),
  requiresReply: boolean('requires_reply').notNull().default(false),
  needsHuman: boolean('needs_human').notNull().default(false),
  status: text('status').$type<'queued' | 'delivered' | 'handled'>().notNull().default('queued'),
  createdAt: now(),
});

// ─── reasoning fingerprint (how the human thinks — not what they did) ───────
export type ReasoningDimension =
  | 'decomposition'        // how they break a problem down (units, backwards from goal, by analogy…)
  | 'starting_point'       // evidence-first vs hypothesis-first; simplest case vs general case
  | 'information'          // what they ask for / trust: examples vs rules, why before how, must see it
  | 'verification'         // how they check themselves: second route, test, move on
  | 'explanation'          // how they like things explained back
  | 'risk'                 // caution, reversibility, when they escalate
  | 'pace'                 // breadth-first exploring vs narrow-and-deep; patience
  | 'other';

/** One reasoning move observed in one conversation. Domain-free by construction. */
export const reasoningObservations = pgTable('reasoning_observations', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  patternKey: text('pattern_key').notNull(),      // snake_case id the extractor reuses across chats
  dimension: text('dimension').$type<ReasoningDimension>().notNull(),
  description: text('description').notNull(),     // one domain-free sentence, present tense
  evidence: jsonb('evidence').$type<Evidence[]>().notNull().default([]),
  weight: real('weight').notNull().default(1),    // negative = counter-evidence ("not me")
  sourceKind: text('source_kind').$type<'conversation' | 'import' | 'feedback'>().notNull(),
  sourceRef: text('source_ref').notNull(),        // conversation id / import conversation uuid
  createdAt: now(),
}, (t) => [index('reasoning_obs_clone_idx').on(t.cloneId, t.patternKey)]);

/** Aggregated pattern: strength grows with repeated, independent evidence and decays over time. */
export const reasoningPatterns = pgTable('reasoning_patterns', {
  cloneId: uuid('clone_id').notNull(),
  patternKey: text('pattern_key').notNull(),
  orgId: text('org_id').notNull(),
  dimension: text('dimension').$type<ReasoningDimension>().notNull(),
  description: text('description').notNull(),
  strength: real('strength').notNull().default(0),
  nSources: integer('n_sources').notNull().default(0),   // distinct conversations that showed it
  status: text('status').$type<'emerging' | 'confirmed' | 'rejected'>().notNull().default('emerging'),
  userVerdict: text('user_verdict').$type<'accept' | 'reject'>(),
  examples: jsonb('examples').$type<string[]>().notNull().default([]),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: updated(),
}, (t) => [primaryKey({ columns: [t.cloneId, t.patternKey] })]);

/** "That's me" / "Not me" on a clone reply. */
export const reasoningFeedback = pgTable('reasoning_feedback', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id').notNull(),
  turnId: uuid('turn_id').notNull(),
  verdict: text('verdict').$type<'me' | 'not_me'>().notNull(),
  comment: text('comment'),
  userId: text('user_id').notNull(),
  createdAt: now(),
}, (t) => [index('reasoning_feedback_clone_idx').on(t.cloneId, t.createdAt)]);

/** claude.ai data-export import runs. */
export const importJobs = pgTable('import_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  filename: text('filename').notNull(),
  status: text('status').$type<'queued' | 'running' | 'done' | 'failed'>().notNull().default('queued'),
  total: integer('total').notNull().default(0),
  processed: integer('processed').notNull().default(0),
  skipped: integer('skipped').notNull().default(0),
  observations: integer('observations').notNull().default(0),
  error: text('error'),
  createdAt: now(),
  updatedAt: updated(),
});

// ─── Claude Code ingestion ──────────────────────────────────────────────────
/** Personal tokens used by the Claude Code SessionEnd hook to post transcripts. Stored hashed. */
export const ingestTokens = pgTable('ingest_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  name: text('name').notNull().default('Claude Code'),
  tokenHash: text('token_hash').notNull().unique(),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: now(),
});

/** One row per Claude Code session we have learned from (dedupe + resume). */
export const claudeCodeSessions = pgTable('claude_code_sessions', {
  cloneId: uuid('clone_id').notNull(),
  sessionId: text('session_id').notNull(),
  orgId: text('org_id').notNull(),
  source: text('source').$type<'local' | 'hook' | 'upload' | 'bridge' | 'claude-chat'>().notNull(),
  project: text('project'),
  bytes: integer('bytes').notNull().default(0),
  humanTurns: integer('human_turns').notNull().default(0),
  observations: integer('observations').notNull().default(0),
  status: text('status').$type<'queued' | 'done' | 'skipped' | 'failed'>().notNull().default('queued'),
  note: text('note'),
  extractedAt: timestamp('extracted_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [primaryKey({ columns: [t.cloneId, t.sessionId] })]);

/** opersona bridge pairing tokens (obr_… , stored as sha256). One row per paired machine. */
export const bridgeTokens = pgTable('bridge_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  userId: text('user_id').notNull(),
  name: text('name').notNull().default('my machine'),
  // Constraint name + plain timestamp match the DDL production was built with (pre-baseline).
  tokenHash: text('token_hash').notNull().unique('bridge_tokens_token_hash_key'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  lastSeenAt: timestamp('last_seen_at'),
  revokedAt: timestamp('revoked_at'),
}, (t) => [index('bridge_tokens_org_idx').on(t.orgId)]);

// ─── self-tests ("does it sound like me?") ──────────────────────────────────
export const selfTests = pgTable('self_tests', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  batchId: uuid('batch_id').notNull(),
  domain: text('domain').notNull().default(''),
  question: text('question').notNull(),
  answer: text('answer').notNull(),
  model: text('model'),
  verdict: text('verdict').$type<'me' | 'not_me'>(),
  comment: text('comment'),
  ratedAt: timestamp('rated_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('self_tests_clone_idx').on(t.cloneId, t.createdAt)]);

// ─── personality (self-reported MBTI-style lens) ────────────────────────────
export const personalityTests = pgTable('personality_tests', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  answers: jsonb('answers').$type<Record<string, number>>().notNull(),
  scores: jsonb('scores').$type<Record<'EI' | 'SN' | 'TF' | 'JP', number>>().notNull(),
  type: text('type').notNull(),
  // 'test' = scored from Likert answers; 'stated' = the owner typed their four
  // letters in directly (scores are ±1 direction sentinels — never render as %).
  source: text('source').$type<'test' | 'stated'>().notNull().default('test'),
  createdAt: now(),
}, (t) => [index('personality_clone_idx').on(t.cloneId, t.createdAt)]);

// auth abuse tracking — per-account lockout (defeats distributed password spray that IP limits miss)
export const authFailures = pgTable('auth_failures', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull(),
  createdAt: now(),
}, (t) => [index('auth_failures_email_idx').on(t.email, t.createdAt)]);

// ─── community: publish / grants / reports / imports (0018) ─────────────────

/** A persona the owner chose to publish. `artifact` is the frozen `opersona/persona@1` snapshot — republish bumps `version` and replaces it. */
export const publishedPersonas = pgTable('published_personas', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull().unique('published_personas_clone_uq'),
  ownerUserId: text('owner_user_id').notNull(),
  slug: text('slug').notNull().unique('published_personas_slug_uq'),
  artifact: jsonb('artifact').$type<PersonaArtifact>().notNull(),
  /** Which sections the owner included at publish time (facts/playbooks/personality toggles). */
  sections: jsonb('sections').$type<Record<string, boolean>>().notNull().default({}),
  /** Owner-sovereign: 'public' (anyone, incl. logged out) or 'restricted' (author + granted people). Private = not published. */
  visibility: text('visibility').$type<'public' | 'restricted'>().notNull().default('restricted'),
  /** 'active' | 'unpublished' (owner took it down) | 'delisted' (moderation). Non-active → /p 404s; existing imports keep working. */
  status: text('status').$type<'active' | 'unpublished' | 'delisted'>().notNull().default('active'),
  version: integer('version').notNull().default(1),
  importCount: integer('import_count').notNull().default(0),
  publishedAt: timestamp('published_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: updated(),
  unpublishedAt: timestamp('unpublished_at', { withTimezone: true }),
}, (t) => [index('published_personas_browse_idx').on(t.visibility, t.status, t.importCount)]);

/** Restricted-visibility access grants, by email (pending until that email has an account). */
export const personaGrants = pgTable('persona_grants', {
  id: uuid('id').primaryKey().defaultRandom(),
  publishedId: uuid('published_id').notNull(),
  granteeEmail: text('grantee_email').notNull(),
  granteeUserId: text('grantee_user_id'),
  createdAt: now(),
}, (t) => [unique('persona_grants_uq').on(t.publishedId, t.granteeEmail), index('persona_grants_pub_idx').on(t.publishedId)]);

export const personaReports = pgTable('persona_reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  publishedId: uuid('published_id').notNull(),
  reporterUserId: text('reporter_user_id'),
  reason: text('reason').notNull(),
  details: text('details'),
  createdAt: now(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  resolution: text('resolution'),
}, (t) => [index('persona_reports_open_idx').on(t.resolvedAt, t.createdAt)]);

/** Provenance for an imported (materialized) persona living as a local clone with kind='imported'. */
export const importedPersonas = pgTable('imported_personas', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull().unique('imported_personas_clone_uq'),
  importedBy: text('imported_by').notNull(),
  sourcePublishedId: uuid('source_published_id'),
  sourceSlug: text('source_slug'),
  sourceVersion: integer('source_version').notNull(),
  artifact: jsonb('artifact').$type<PersonaArtifact>().notNull(),
  createdAt: now(),
  updatedAt: updated(),
}, (t) => [index('imported_personas_org_idx').on(t.orgId)]);

// ─── cognitive interview + knowledge model (P2) ─────────────────────────────
// The interview asks behavioural questions across ten life categories; every
// answer is analysed into MEMORIES (things that happened), TRAITS (values /
// beliefs / preferences / behaviours / decision patterns) and CONTEXTUAL RULES
// (IF situation AND condition THEN tendency). Each learned item carries the
// provenance spine PLUS an epistemic `tier`: 'explicit' (they plainly said it),
// 'inferred' (observed across answers), 'hypothesis' (suspected). Tiers never
// auto-promote — only new explicit quoted evidence or an owner verdict moves one.

export type InterviewQuestionKind = 'behavioural' | 'follow_up' | 'contradiction';
export type InterviewQuestionSource = 'bank' | 'generated' | 'triage';
export type InterviewQuestionStatus = 'pending' | 'asked' | 'answered' | 'skipped' | 'retired';
export type EpistemicTier = 'explicit' | 'inferred' | 'hypothesis';
export type TraitKind = 'value' | 'belief' | 'preference' | 'behaviour' | 'decision_pattern';

export const interviewQuestions = pgTable('interview_questions', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  category: text('category').notNull(),
  /** Sub-area within the category the question probes (bank facets; nullable for follow-ups). */
  facet: text('facet'),
  text: text('text').notNull(),
  /** One quiet line under the question ("a real moment beats a general answer"). */
  hint: text('hint'),
  kind: text('kind').$type<InterviewQuestionKind>().notNull().default('behavioural'),
  source: text('source').$type<InterviewQuestionSource>().notNull().default('bank'),
  /** Follow-up intent (why | alternatives | what_mattered | would_you_today | exception | close_person). */
  intent: text('intent'),
  parentAnswerId: uuid('parent_answer_id'),
  contradictionId: uuid('contradiction_id'),
  /** Stable bank id so an opener is materialized at most once per clone. */
  bankKey: text('bank_key'),
  status: text('status').$type<InterviewQuestionStatus>().notNull().default('pending'),
  priority: real('priority').notNull().default(0),
  askedAt: timestamp('asked_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [
  index('interview_questions_clone_status_idx').on(t.cloneId, t.status),
  uniqueIndex('interview_questions_bank_uq').on(t.cloneId, t.bankKey).where(sql`bank_key is not null`),
]);

export const interviewAnswers = pgTable('interview_answers', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  questionId: uuid('question_id').notNull(),
  /** Denormalized so the answer stays self-describing even if the question is retired. */
  category: text('category').notNull(),
  questionText: text('question_text').notNull(),
  text: text('text').notNull().default(''),
  skipped: boolean('skipped').notNull().default(false),
  context: jsonb('context').$type<{ threadDepth?: number; intent?: string | null; dialogue?: { role: string; text: string }[] }>().notNull().default({}),
  /** Edits never erase: prior versions pushed here. */
  revisions: jsonb('revisions').$type<{ text: string; at: string }[]>().notNull().default([]),
  /** Summary of what the async pass extracted (for the answer history UI). */
  extraction: jsonb('extraction').$type<{ memories: number; traits: number; rules: number; tensions: number; quality: string; note: string } | null>().default(null),
  extractionStatus: text('extraction_status').$type<'pending' | 'done' | 'failed' | 'skipped'>().notNull().default('pending'),
  extractedAt: timestamp('extracted_at', { withTimezone: true }),
  editedAt: timestamp('edited_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [
  index('interview_answers_clone_idx').on(t.cloneId, t.createdAt),
  index('interview_answers_extract_idx').on(t.cloneId, t.extractionStatus),
]);

/** Life memories — things that HAPPENED, separate from behaviour patterns.
 *  "Moved cities in 2024 for work" is a memory; "willing to relocate for career
 *  upside" is a trait. */
export const memories = pgTable('memories', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  summary: text('summary').notNull(),
  fullContext: text('full_context').notNull().default(''),
  importance: real('importance').notNull().default(0.5),
  emotionalSignificance: real('emotional_significance').notNull().default(0),
  peopleInvolved: text('people_involved').array().notNull().default(sql`'{}'::text[]`),
  /** Verbatim fuzzy period as the person said it ("2024", "when I was a kid"). */
  dateOrPeriod: text('date_or_period'),
  periodStart: timestamp('period_start', { withTimezone: true }),
  periodEnd: timestamp('period_end', { withTimezone: true }),
  category: text('category'),
  shareable: boolean('shareable').notNull().default(false),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(summary,'') || ' ' || coalesce(full_context,'') || ' ' || coalesce(date_or_period,''))`),
}, (t) => [
  index('memories_clone_idx').on(t.cloneId, t.status),
  index('memories_tsv_idx').using('gin', t.tsv),
]);

/** Values / beliefs / preferences / behaviours / decision patterns, keyed for
 *  reinforcement (same key ⇒ evidence accumulates instead of duplicating). */
export const traits = pgTable('traits', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  kind: text('kind').$type<TraitKind>().notNull(),
  key: text('key').notNull(),
  /** Short display name, e.g. "Independence". */
  label: text('label').notNull(),
  /** One-sentence statement of the trait. */
  statement: text('statement').notNull(),
  category: text('category'),
  tier: text('tier').$type<EpistemicTier>().notNull(),
  /** How strongly held (≠ confidence, which is how sure WE are). */
  strength: real('strength').notNull().default(0.5),
  contexts: text('contexts').array().notNull().default(sql`'{}'::text[]`),
  shareable: boolean('shareable').notNull().default(false),
  validFrom: timestamp('valid_from', { withTimezone: true }),
  validUntil: timestamp('valid_until', { withTimezone: true }),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(label,'') || ' ' || coalesce(statement,'') || ' ' || coalesce(category,''))`),
}, (t) => [
  uniqueIndex('traits_clone_kind_key_uq').on(t.cloneId, t.kind, t.key),
  index('traits_clone_idx').on(t.cloneId, t.status),
  index('traits_tsv_idx').using('gin', t.tsv),
]);

/** Conditional behaviour: IF situation (AND condition) THEN tendency. The
 *  simulation consults these — and exceptions — before predicting. */
export const contextualRules = pgTable('contextual_rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  category: text('category'),
  situation: text('situation').notNull(),
  condition: text('condition'),
  tendency: text('tendency').notNull(),
  /** When this rule is an exception to a trait, the trait it bends. */
  exceptionToTraitId: uuid('exception_to_trait_id'),
  tier: text('tier').$type<'explicit' | 'inferred'>().notNull(),
  shareable: boolean('shareable').notNull().default(false),
  validFrom: timestamp('valid_from', { withTimezone: true }),
  validUntil: timestamp('valid_until', { withTimezone: true }),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(situation,'') || ' ' || coalesce(condition,'') || ' ' || coalesce(tendency,''))`),
}, (t) => [
  index('contextual_rules_clone_idx').on(t.cloneId, t.status),
  index('contextual_rules_tsv_idx').using('gin', t.tsv),
]);

/** Detected tensions between what the model believes and a new answer — each
 *  gets a targeted probe question; a resolution usually becomes a contextual rule. */
export const contradictions = pgTable('contradictions', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  traitId: uuid('trait_id'),
  answerId: uuid('answer_id').notNull(),
  description: text('description').notNull(),
  probeQuestionId: uuid('probe_question_id'),
  status: text('status').$type<'open' | 'probed' | 'resolved' | 'dismissed'>().notNull().default('open'),
  resolutionAnswerId: uuid('resolution_answer_id'),
  resolutionNote: text('resolution_note'),
  createdAt: now(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
}, (t) => [index('contradictions_clone_status_idx').on(t.cloneId, t.status)]);

/** Per-category coverage cache, recomputed after each extraction. */
export const interviewCoverage = pgTable('interview_coverage', {
  cloneId: uuid('clone_id').notNull(),
  category: text('category').notNull(),
  orgId: text('org_id').notNull(),
  coverage: real('coverage').notNull().default(0),
  facets: jsonb('facets').$type<Record<string, number>>().notNull().default({}),
  answered: integer('answered').notNull().default(0),
  openContradictions: integer('open_contradictions').notNull().default(0),
  updatedAt: updated(),
}, (t) => [primaryKey({ columns: [t.cloneId, t.category] })]);

/** Vendor-free embedding store (written only when EMBEDDINGS_PROVIDER is set;
 *  FTS stays the default retrieval). vec is jsonb so a later pgvector swap is a
 *  column change, not a schema redesign. */
export const knowledgeEmbeddings = pgTable('knowledge_embeddings', {
  itemKind: text('item_kind').$type<'memory' | 'trait' | 'rule'>().notNull(),
  itemId: uuid('item_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  orgId: text('org_id').notNull(),
  provider: text('provider').notNull(),
  model: text('model').notNull(),
  dim: integer('dim').notNull(),
  vec: jsonb('vec').$type<number[]>().notNull(),
  createdAt: now(),
}, (t) => [primaryKey({ columns: [t.itemKind, t.itemId] }), index('knowledge_embeddings_clone_idx').on(t.cloneId)]);

// ─── blind prediction tests (P4) ────────────────────────────────────────────
// The self-honesty loop: the model predicts BLIND (at scenario creation, sealed
// until the person commits their own answer — predicted_at < answered_at is a
// stored invariant), then an LLM judge scores the match across dimensions.
// Operational like self_tests, NOT spine(): a test artifact, not a learned layer.

export interface ScenarioPrediction { decision: string; factors: string[]; communication: string; confidence: number }
export interface ScenarioJudgeOut { rationale: Record<string, string>; key_differences: string[]; summary: string }

export const predictionScenarios = pgTable('prediction_scenarios', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  batchId: uuid('batch_id').notNull(),
  category: text('category').notNull(),
  format: text('format').$type<'open' | 'choice'>().notNull().default('open'),
  choices: text('choices').array().notNull().default(sql`'{}'::text[]`),
  scenario: text('scenario').notNull(),
  question: text('question').notNull(),
  /** Why this scenario was generated (which weak/uncertain areas it targets). */
  targetNote: text('target_note'),
  targetRefs: jsonb('target_refs').$type<{ kind: string; ref: string; hint?: string }[]>().notNull().default([]),
  snapshotVersion: integer('snapshot_version'),
  model: text('model'),
  // Sealed until answered — never selected into any open-scenario payload.
  aiPrediction: jsonb('ai_prediction').$type<ScenarioPrediction>(),
  predictedAt: timestamp('predicted_at', { withTimezone: true }),
  // State machine: open → answered → scored | failed ; open → skipped.
  status: text('status').$type<'open' | 'answered' | 'scored' | 'skipped' | 'failed'>().notNull().default('open'),
  humanAnswer: text('human_answer'),
  humanFactors: text('human_factors'),
  answeredAt: timestamp('answered_at', { withTimezone: true }),
  judge: jsonb('judge').$type<ScenarioJudgeOut>(),
  scoreDecision: real('score_decision'),
  scoreReasoning: real('score_reasoning'),
  scorePreference: real('score_preference'),
  scoreCommunication: real('score_communication'),
  scoreCalibration: real('score_calibration'),
  scoreOverall: real('score_overall'),
  judgeModel: text('judge_model'),
  judgedAt: timestamp('judged_at', { withTimezone: true }),
  correctionId: uuid('correction_id'),
  createdAt: now(),
}, (t) => [
  index('pred_scenarios_clone_status_idx').on(t.cloneId, t.status),
  index('pred_scenarios_clone_idx').on(t.cloneId, t.createdAt),
]);

// ─── simulations (P5) ───────────────────────────────────────────────────────
// One-shot behavioural predictions ("what would I do?"). Deliberately NOT
// conversations: server-assembled context, structured output, and the learning
// queue never mines them (they are the persona talking, not the human).

export interface SimulationOutput {
  answer: string;
  factors: { factor: string; weight: 'major' | 'minor' }[];
  confidence: number;
  uncertainty: string[];
  evidence_used: string[];
  enough_information: boolean;
  comparison?: { option: string; verdict: string; lean: number }[];
}

export const simulations = pgTable('simulations', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  mode: text('mode').$type<'ask' | 'respond' | 'decide' | 'compare' | 'explain'>().notNull(),
  input: jsonb('input').$type<{ text: string; options?: string[]; context?: string }>().notNull(),
  output: jsonb('output').$type<SimulationOutput>().notNull(),
  /** The retrieval hits that were OFFERED to the model (evidence_used ⊆ these ids). */
  evidence: jsonb('evidence').$type<{ layer: string; id: string; text: string }[]>().notNull().default([]),
  model: text('model'),
  createdAt: now(),
}, (t) => [index('simulations_clone_idx').on(t.cloneId, t.createdAt)]);

/** Chat-style interview: the persona messages its human; short exchanges per
 *  question. When a thread wraps, the user side materializes into an
 *  interview_answers row (same extraction pipeline; quotes stay verifiable
 *  against the person's own words). */
export const interviewMessages = pgTable('interview_messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  questionId: uuid('question_id').notNull(),
  role: text('role').$type<'interviewer' | 'user'>().notNull(),
  text: text('text').notNull(),
  createdAt: now(),
}, (t) => [index('interview_messages_thread_idx').on(t.cloneId, t.questionId, t.createdAt)]);
