/**
 * Application schema. Auth tables (user/session/organization/member/…) are
 * generated by better-auth into ./auth-schema.ts and referenced here by id.
 *
 * Every learned row carries the PROVENANCE SPINE (see `spine()`): status,
 * confidence, source, verbatim evidence. Nothing about a human is ever stored
 * without saying where it came from.
 */
import { sql } from 'drizzle-orm';
import {
  pgTable, text, timestamp, boolean, integer, real, jsonb, uuid, primaryKey, index, uniqueIndex, customType,
} from 'drizzle-orm/pg-core';
import type { AvatarRecipe } from '@opersona/shared';

// ─── helpers ────────────────────────────────────────────────────────────────
import { randomBytes } from 'node:crypto';
const ALPHABET = 'abcdefghijkmnpqrstuvwxyz23456789'; // no 0/o/1/l
export function shortId(len = 7): string { const b = randomBytes(len); let s = ''; for (let i = 0; i < len; i++) s += ALPHABET[b[i]! % ALPHABET.length]; return s; }
const tsvector = customType<{ data: string }>({ dataType: () => 'tsvector' });
const now = () => timestamp('created_at', { withTimezone: true }).defaultNow().notNull();
const updated = () => timestamp('updated_at', { withTimezone: true }).defaultNow().notNull();

export type LearnedStatus = 'candidate' | 'confirmed' | 'disputed' | 'retired';
export type SourceKind = 'conversation' | 'teach' | 'correction' | 'document' | 'reflection' | 'admin';
export interface Evidence { quote: string; turn_id?: string }

/** Provenance spine mixed into every learned-layer table. */
const spine = () => ({
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  status: text('status').$type<LearnedStatus>().notNull().default('candidate'),
  confidence: real('confidence').notNull().default(0.5),
  sourceKind: text('source_kind').$type<SourceKind>().notNull(),
  sourceRef: text('source_ref'),
  evidence: jsonb('evidence').$type<Evidence[]>().notNull().default([]),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
  updatedAt: updated(),
  lastReinforcedAt: timestamp('last_reinforced_at', { withTimezone: true }),
  reinforceCount: integer('reinforce_count').notNull().default(0),
  supersedes: uuid('supersedes'),
});

// ─── org settings ───────────────────────────────────────────────────────────
export const orgSettings = pgTable('org_settings', {
  orgId: text('org_id').primaryKey(),
  /** AES-GCM encrypted Anthropic API key (BYO). null → platform key. */
  anthropicKeyEnc: text('anthropic_key_enc'),
  chatModel: text('chat_model').notNull().default('claude-opus-5'),
  extractModel: text('extract_model').notNull().default('claude-sonnet-5'),
  condenseModel: text('condense_model').notNull().default('claude-haiku-4-5'),
  chatEffort: text('chat_effort').notNull().default('high'),
  monthlyBudgetUsd: real('monthly_budget_usd'),
  timezone: text('timezone').notNull().default('UTC'),
  updatedAt: updated(),
});

// ─── clones ─────────────────────────────────────────────────────────────────
export const clones = pgTable('clones', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  ownerUserId: text('owner_user_id').notNull(),
  name: text('name').notNull(),
  avatarRecipe: jsonb('avatar_recipe').$type<AvatarRecipe>(),
  activeSnapshotId: uuid('active_snapshot_id'),
  createdAt: now(),
  updatedAt: updated(),
}, (t) => [
  uniqueIndex('clones_org_owner_uq').on(t.orgId, t.ownerUserId),
  index('clones_org_idx').on(t.orgId),
]);

export const personaBriefs = pgTable('persona_briefs', {
  cloneId: uuid('clone_id').primaryKey(),
  orgId: text('org_id').notNull(),
  displayName: text('display_name').notNull().default(''),
  roleTitle: text('role_title').notNull().default(''),
  team: text('team').notNull().default(''),
  briefMd: text('brief_md').notNull().default(''),
  operatingRules: text('operating_rules').notNull().default(''),
  version: integer('version').notNull().default(1),
  updatedAt: updated(),
});

// ─── learned layers ─────────────────────────────────────────────────────────
export const facts = pgTable('facts', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  statement: text('statement').notNull(),
  tags: text('tags').array().notNull().default(sql`'{}'::text[]`),
  domain: text('domain'),
  pinned: boolean('pinned').notNull().default(false),
  shareable: boolean('shareable').notNull().default(false),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(statement,'') || ' ' || coalesce(domain,''))`),
}, (t) => [
  index('facts_clone_idx').on(t.cloneId, t.status),
  index('facts_tsv_idx').using('gin', t.tsv),
]);

export interface PlaybookStep { n: number; action: string; command?: string; check?: string; expected?: string; if_not?: string }
export const playbooks = pgTable('playbooks', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  name: text('name').notNull(),
  domain: text('domain'),
  version: integer('version').notNull().default(1),
  trigger: text('trigger').notNull(),
  preconditions: text('preconditions').array().notNull().default(sql`'{}'::text[]`),
  steps: jsonb('steps').$type<PlaybookStep[]>().notNull().default([]),
  pitfalls: text('pitfalls').array().notNull().default(sql`'{}'::text[]`),
  outcomeStats: jsonb('outcome_stats').$type<{ used: number; succeeded: number; failed: number }>().notNull().default({ used: 0, succeeded: 0, failed: 0 }),
  sourceEpisodeIds: uuid('source_episode_ids').array().notNull().default(sql`'{}'::uuid[]`),
  shareable: boolean('shareable').notNull().default(true),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(name,'') || ' ' || coalesce(trigger,'') || ' ' || coalesce(domain,''))`),
}, (t) => [
  index('playbooks_clone_idx').on(t.cloneId, t.status),
  index('playbooks_tsv_idx').using('gin', t.tsv),
]);

export const playbookRevisions = pgTable('playbook_revisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  playbookId: uuid('playbook_id').notNull(),
  version: integer('version').notNull(),
  snapshot: jsonb('snapshot').notNull(),
  diff: text('diff'),
  reason: text('reason'),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
});

export type StyleDimension = 'approach' | 'verbosity' | 'tools_preferred' | 'risk_tolerance' | 'escalation' | 'verification' | 'communication';
export interface StyleDimensionValue { value: string | string[]; score?: number; n: number; confidence: number; examples: string[] }
export const styleProfiles = pgTable('style_profiles', {
  cloneId: uuid('clone_id').primaryKey(),
  orgId: text('org_id').notNull(),
  version: integer('version').notNull().default(1),
  dimensions: jsonb('dimensions').$type<Partial<Record<StyleDimension, StyleDimensionValue>>>().notNull().default({}),
  overrides: jsonb('overrides').$type<Partial<Record<StyleDimension, string>>>().notNull().default({}),
  renderedMd: text('rendered_md').notNull().default(''),
  updatedAt: updated(),
});

export const styleObservations = pgTable('style_observations', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  dimension: text('dimension').$type<StyleDimension>().notNull(),
  observedValue: text('observed_value').notNull(),
  weight: real('weight').notNull().default(1),
}, (t) => [index('style_obs_clone_idx').on(t.cloneId, t.dimension)]);

export const episodes = pgTable('episodes', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  conversationId: uuid('conversation_id'),
  domain: text('domain'),
  title: text('title').notNull(),
  problem: text('problem').notNull().default(''),
  approachSummary: text('approach_summary').notNull().default(''),
  keyDecisions: text('key_decisions').array().notNull().default(sql`'{}'::text[]`),
  outcome: text('outcome').$type<'resolved' | 'partial' | 'unresolved' | 'unknown'>().notNull().default('unknown'),
  durationS: integer('duration_s'),
  turnCount: integer('turn_count'),
  playbookIds: uuid('playbook_ids').array().notNull().default(sql`'{}'::uuid[]`),
  factIds: uuid('fact_ids').array().notNull().default(sql`'{}'::uuid[]`),
  condensed: boolean('condensed').notNull().default(false),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(title,'') || ' ' || coalesce(problem,'') || ' ' || coalesce(approach_summary,''))`),
}, (t) => [
  index('episodes_clone_idx').on(t.cloneId, t.createdAt),
  index('episodes_tsv_idx').using('gin', t.tsv),
]);

export const condensedHistory = pgTable('condensed_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  domain: text('domain').notNull().default('general'),
  summaryMd: text('summary_md').notNull().default(''),
  coversEpisodeIds: uuid('covers_episode_ids').array().notNull().default(sql`'{}'::uuid[]`),
  version: integer('version').notNull().default(1),
  updatedAt: updated(),
}, (t) => [uniqueIndex('condensed_clone_domain_uq').on(t.cloneId, t.domain)]);

export const corrections = pgTable('corrections', {
  id: uuid('id').primaryKey().defaultRandom(),
  ...spine(),
  conversationId: uuid('conversation_id'),
  taskId: uuid('task_id'),
  turnId: uuid('turn_id'),
  cloneOutput: text('clone_output').notNull().default(''),
  humanFix: text('human_fix').notNull().default(''),
  diff: text('diff'),
  kind: text('kind').$type<'factual' | 'procedural' | 'stylistic' | 'scope' | 'one_off'>().notNull().default('one_off'),
  severity: text('severity').$type<'low' | 'medium' | 'high'>().notNull().default('low'),
  lesson: text('lesson').notNull().default(''),
  scope: jsonb('scope').$type<{ domain?: string; task_type?: string }>().notNull().default({}),
  applied: jsonb('applied').$type<{ layer: string; id: string; action: string }[]>().notNull().default([]),
  standing: boolean('standing').notNull().default(false),
}, (t) => [index('corrections_clone_idx').on(t.cloneId, t.standing)]);

export const autonomyLedger = pgTable('autonomy_ledger', {
  cloneId: uuid('clone_id').notNull(),
  orgId: text('org_id').notNull(),
  taskType: text('task_type').notNull(),
  level: integer('level').notNull().default(1),
  approvedClean: integer('approved_clean').notNull().default(0),
  approvedEdited: integer('approved_edited').notNull().default(0),
  rejected: integer('rejected').notNull().default(0),
  streakClean: integer('streak_clean').notNull().default(0),
  adminCap: integer('admin_cap'),
  lastChangeAt: timestamp('last_change_at', { withTimezone: true }),
  lastChangeReason: text('last_change_reason'),
}, (t) => [primaryKey({ columns: [t.cloneId, t.taskType] })]);

export const taskReviews = pgTable('task_reviews', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  taskId: uuid('task_id').notNull(),
  taskType: text('task_type').notNull(),
  verdict: text('verdict').$type<'approved' | 'edited' | 'rejected'>().notNull(),
  editDistance: integer('edit_distance'),
  comment: text('comment'),
  reviewerUserId: text('reviewer_user_id').notNull(),
  createdAt: now(),
});

// ─── cross-cutting ──────────────────────────────────────────────────────────
export const learningEvents = pgTable('learning_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  layer: text('layer').notNull(), // fact | playbook | style | episode | correction | autonomy | brief
  targetId: text('target_id'),
  action: text('action').notNull(), // created | updated | merged | retired | disputed | promoted | demoted
  summary: text('summary').notNull(),
  before: jsonb('before'),
  after: jsonb('after'),
  confidence: real('confidence'),
  sourceKind: text('source_kind').$type<SourceKind>(),
  sourceRef: text('source_ref'),
  reviewStatus: text('review_status').$type<'pending' | 'accepted' | 'rejected' | 'edited' | 'auto'>().notNull().default('pending'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('learning_events_clone_idx').on(t.cloneId, t.reviewStatus, t.createdAt)]);

export const rejectedProposals = pgTable('rejected_proposals', {
  id: uuid('id').primaryKey().defaultRandom(),
  cloneId: uuid('clone_id').notNull(),
  layer: text('layer').notNull(),
  text: text('text').notNull(),
  createdAt: now(),
});

export const personaSnapshots = pgTable('persona_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  version: integer('version').notNull(),
  renderedPrompt: text('rendered_prompt').notNull(),
  promptHash: text('prompt_hash').notNull(),
  tokenEstimate: integer('token_estimate'),
  layerVersions: jsonb('layer_versions').notNull().default({}),
  reflectionRunId: uuid('reflection_run_id'),
  createdAt: now(),
}, (t) => [uniqueIndex('snapshots_clone_version_uq').on(t.cloneId, t.version)]);

export const reflectionRuns = pgTable('reflection_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  startedAt: now(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  status: text('status').$type<'running' | 'done' | 'aborted' | 'skipped'>().notNull().default('running'),
  reason: text('reason'),
  stats: jsonb('stats').notNull().default({}),
  backupRef: text('backup_ref'),
});

// ─── documents ──────────────────────────────────────────────────────────────
export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id'), // null → org-wide KB
  filename: text('filename').notNull(),
  mime: text('mime').notNull(),
  bytes: integer('bytes').notNull(),
  trust: text('trust').notNull().default('untrusted'),
  uploadedBy: text('uploaded_by').notNull(),
  createdAt: now(),
}, (t) => [index('documents_org_idx').on(t.orgId, t.cloneId)]);

export const documentChunks = pgTable('document_chunks', {
  id: uuid('id').primaryKey().defaultRandom(),
  documentId: uuid('document_id').notNull(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id'),
  ord: integer('ord').notNull(),
  content: text('content').notNull(),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('english', coalesce(content,''))`),
}, (t) => [
  index('chunks_doc_idx').on(t.documentId, t.ord),
  index('chunks_tsv_idx').using('gin', t.tsv),
]);

// ─── conversations ──────────────────────────────────────────────────────────
export const conversations = pgTable('conversations', {
  pinned: boolean('pinned').notNull().default(false),
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  /** Short public id for URLs (/c/<slug>). */
  slug: text('slug').notNull().unique().$defaultFn(() => shortId()),
  title: text('title').notNull().default('New conversation'),
  sdkSessionId: text('sdk_session_id'),
  /** claude = plain Claude (the persona only learns from it); clone = answer AS the clone (to test it). */
  mode: text('mode').$type<'claude' | 'clone'>().notNull().default('claude'),
  /** Per-conversation overrides; null → org default. */
  model: text('model'),
  effort: text('effort').$type<'low' | 'medium' | 'high' | 'xhigh' | 'max'>(),
  status: text('status').$type<'live' | 'idle' | 'closed'>().notNull().default('idle'),
  /** Per-conversation working directory for code execution + file outputs (null = legacy per-clone workspace). */
  cwd: text('cwd'),
  extractedAt: timestamp('extracted_at', { withTimezone: true }),
  lastActivityAt: timestamp('last_activity_at', { withTimezone: true }).defaultNow().notNull(),
  createdAt: now(),
}, (t) => [index('conversations_clone_idx').on(t.cloneId, t.lastActivityAt)]);

export const turns = pgTable('turns', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id').notNull(),
  orgId: text('org_id').notNull(),
  role: text('role').$type<'user' | 'assistant' | 'system'>().notNull(),
  content: text('content').notNull(), // redacted
  toolUses: jsonb('tool_uses').$type<{ id: string; name: string; input: unknown; ok?: boolean; preview?: string }[]>().notNull().default([]),
  /** Files created/changed in the conversation workdir during this assistant turn. */
  files: jsonb('files').$type<{ path: string; size: number }[]>(),
  editedContent: text('edited_content'),
  createdAt: now(),
}, (t) => [index('turns_conv_idx').on(t.conversationId, t.createdAt)]);

export const sessionCosts = pgTable('session_costs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id'),
  kind: text('kind').notNull().default('chat'), // chat | extract | reflect | avatar | task
  model: text('model'),
  promptHash: text('prompt_hash'),
  inputTokens: integer('input_tokens').notNull().default(0),
  outputTokens: integer('output_tokens').notNull().default(0),
  cacheReadInputTokens: integer('cache_read_input_tokens').notNull().default(0),
  cacheCreationInputTokens: integer('cache_creation_input_tokens').notNull().default(0),
  costUsd: real('cost_usd'),
  createdAt: now(),
}, (t) => [index('session_costs_org_idx').on(t.orgId, t.createdAt)]);

export const approvals = pgTable('approvals', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id'),
  kind: text('kind').$type<'tool' | 'question'>().notNull().default('tool'),
  tool: text('tool'),
  input: jsonb('input'),
  question: text('question'),
  options: text('options').array(),
  status: text('status').$type<'pending' | 'allowed' | 'denied' | 'answered' | 'expired'>().notNull().default('pending'),
  answer: text('answer'),
  updatedInput: jsonb('updated_input'),
  resolvedBy: text('resolved_by'),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('approvals_clone_idx').on(t.cloneId, t.status)]);

// ─── tasks (Phase 2) ────────────────────────────────────────────────────────
export const tasks = pgTable('tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  taskType: text('task_type').notNull(),
  spec: text('spec').notNull(),
  input: jsonb('input'),
  status: text('status').$type<'queued' | 'running' | 'awaiting_review' | 'approved' | 'edited' | 'rejected' | 'done' | 'failed'>().notNull().default('queued'),
  output: text('output'),
  autonomyLevelAtRun: integer('autonomy_level_at_run'),
  createdBy: text('created_by').notNull(),
  createdAt: now(),
  updatedAt: updated(),
});

// ─── inter-clone messages (Phase 3) ─────────────────────────────────────────
export const cloneMessages = pgTable('clone_messages', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  conversation: text('conversation').notNull(),
  inReplyTo: text('in_reply_to'),
  from: uuid('from_clone').notNull(),
  to: text('to_clone').notNull(),
  act: text('act').notNull(),
  subject: text('subject').notNull(),
  body: text('body').notNull(),
  hops: integer('hops').notNull().default(0),
  requiresReply: boolean('requires_reply').notNull().default(false),
  needsHuman: boolean('needs_human').notNull().default(false),
  status: text('status').$type<'queued' | 'delivered' | 'handled'>().notNull().default('queued'),
  createdAt: now(),
});

// ─── reasoning fingerprint (how the human thinks — not what they did) ───────
export type ReasoningDimension =
  | 'decomposition'        // how they break a problem down (units, backwards from goal, by analogy…)
  | 'starting_point'       // evidence-first vs hypothesis-first; simplest case vs general case
  | 'information'          // what they ask for / trust: examples vs rules, why before how, must see it
  | 'verification'         // how they check themselves: second route, test, move on
  | 'explanation'          // how they like things explained back
  | 'risk'                 // caution, reversibility, when they escalate
  | 'pace'                 // breadth-first exploring vs narrow-and-deep; patience
  | 'other';

/** One reasoning move observed in one conversation. Domain-free by construction. */
export const reasoningObservations = pgTable('reasoning_observations', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  patternKey: text('pattern_key').notNull(),      // snake_case id the extractor reuses across chats
  dimension: text('dimension').$type<ReasoningDimension>().notNull(),
  description: text('description').notNull(),     // one domain-free sentence, present tense
  evidence: jsonb('evidence').$type<Evidence[]>().notNull().default([]),
  weight: real('weight').notNull().default(1),    // negative = counter-evidence ("not me")
  sourceKind: text('source_kind').$type<'conversation' | 'import' | 'feedback'>().notNull(),
  sourceRef: text('source_ref').notNull(),        // conversation id / import conversation uuid
  createdAt: now(),
}, (t) => [index('reasoning_obs_clone_idx').on(t.cloneId, t.patternKey)]);

/** Aggregated pattern: strength grows with repeated, independent evidence and decays over time. */
export const reasoningPatterns = pgTable('reasoning_patterns', {
  cloneId: uuid('clone_id').notNull(),
  patternKey: text('pattern_key').notNull(),
  orgId: text('org_id').notNull(),
  dimension: text('dimension').$type<ReasoningDimension>().notNull(),
  description: text('description').notNull(),
  strength: real('strength').notNull().default(0),
  nSources: integer('n_sources').notNull().default(0),   // distinct conversations that showed it
  status: text('status').$type<'emerging' | 'confirmed' | 'rejected'>().notNull().default('emerging'),
  userVerdict: text('user_verdict').$type<'accept' | 'reject'>(),
  examples: jsonb('examples').$type<string[]>().notNull().default([]),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: updated(),
}, (t) => [primaryKey({ columns: [t.cloneId, t.patternKey] })]);

/** "That's me" / "Not me" on a clone reply. */
export const reasoningFeedback = pgTable('reasoning_feedback', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  conversationId: uuid('conversation_id').notNull(),
  turnId: uuid('turn_id').notNull(),
  verdict: text('verdict').$type<'me' | 'not_me'>().notNull(),
  comment: text('comment'),
  userId: text('user_id').notNull(),
  createdAt: now(),
}, (t) => [index('reasoning_feedback_clone_idx').on(t.cloneId, t.createdAt)]);

/** claude.ai data-export import runs. */
export const importJobs = pgTable('import_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  filename: text('filename').notNull(),
  status: text('status').$type<'queued' | 'running' | 'done' | 'failed'>().notNull().default('queued'),
  total: integer('total').notNull().default(0),
  processed: integer('processed').notNull().default(0),
  skipped: integer('skipped').notNull().default(0),
  observations: integer('observations').notNull().default(0),
  error: text('error'),
  createdAt: now(),
  updatedAt: updated(),
});

// ─── Claude Code ingestion ──────────────────────────────────────────────────
/** Personal tokens used by the Claude Code SessionEnd hook to post transcripts. Stored hashed. */
export const ingestTokens = pgTable('ingest_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  userId: text('user_id').notNull(),
  name: text('name').notNull().default('Claude Code'),
  tokenHash: text('token_hash').notNull().unique(),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: now(),
});

/** One row per Claude Code session we have learned from (dedupe + resume). */
export const claudeCodeSessions = pgTable('claude_code_sessions', {
  cloneId: uuid('clone_id').notNull(),
  sessionId: text('session_id').notNull(),
  orgId: text('org_id').notNull(),
  source: text('source').$type<'local' | 'hook' | 'upload'>().notNull(),
  project: text('project'),
  bytes: integer('bytes').notNull().default(0),
  humanTurns: integer('human_turns').notNull().default(0),
  observations: integer('observations').notNull().default(0),
  status: text('status').$type<'queued' | 'done' | 'skipped' | 'failed'>().notNull().default('queued'),
  note: text('note'),
  extractedAt: timestamp('extracted_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [primaryKey({ columns: [t.cloneId, t.sessionId] })]);

// ─── self-tests ("does it sound like me?") ──────────────────────────────────
export const selfTests = pgTable('self_tests', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  batchId: uuid('batch_id').notNull(),
  domain: text('domain').notNull().default(''),
  question: text('question').notNull(),
  answer: text('answer').notNull(),
  model: text('model'),
  verdict: text('verdict').$type<'me' | 'not_me'>(),
  comment: text('comment'),
  ratedAt: timestamp('rated_at', { withTimezone: true }),
  createdAt: now(),
}, (t) => [index('self_tests_clone_idx').on(t.cloneId, t.createdAt)]);

// ─── personality (self-reported MBTI-style lens) ────────────────────────────
export const personalityTests = pgTable('personality_tests', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: text('org_id').notNull(),
  cloneId: uuid('clone_id').notNull(),
  answers: jsonb('answers').$type<Record<string, number>>().notNull(),
  scores: jsonb('scores').$type<Record<'EI' | 'SN' | 'TF' | 'JP', number>>().notNull(),
  type: text('type').notNull(),
  createdAt: now(),
}, (t) => [index('personality_clone_idx').on(t.cloneId, t.createdAt)]);

// auth abuse tracking — per-account lockout (defeats distributed password spray that IP limits miss)
export const authFailures = pgTable('auth_failures', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull(),
  createdAt: now(),
}, (t) => [index('auth_failures_email_idx').on(t.email, t.createdAt)]);
